apiVersion: v1
kind: Template
labels:
        template: ocp-minio-persistent-template
message: |-
  The following service(s) have been created in your project: ${MINIO_SERVICE_NAME}.

metadata:
  annotations:
    description: |-
      Minio object storage server, with persistent storage.

      NOTE: Scaling to more than one replica is not supported. You must have persistent volumes available in your cluster to use this template.
    iconClass: icon-minio
    openshift.io/display-name: OCP-Minio (Persistent)
    tags: minio
    template.openshift.io/provider-display-name: SDP Team
    template.openshift.io/support-url: https://svcmgr.cdc.gov/
  creationTimestamp: null
  name: ocp-minio-persistent
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${MINIO_SERVICE_NAME}
  stringData:
    minio-access-key: ${MINIO_ACCESS_KEY}
    minio-secret-key: ${MINIO_SECRET_KEY}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${MINIO_SERVICE_NAME}
  spec:
    ports:
    - name: minio
      nodePort: 0
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      name: ${MINIO_SERVICE_NAME}
    sessionAffinity: None
    type: LoadBalancer
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${MINIO_SERVICE_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${MINIO_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${MINIO_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${MINIO_SERVICE_NAME}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: minio-access-key
                name: ${MINIO_SERVICE_NAME}
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: minio-secret-key
                name: ${MINIO_SERVICE_NAME}
          image: ' '
          imagePullPolicy: IfNotPresent
          args:
          - server
          - --config-dir
          - /export/.minio
          - /export
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          name: minio
          ports:
          - containerPort: 9000
            protocol: TCP
          readinessProbe:
            initialDelaySeconds: 3
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /export
            name: export
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: export
          persistentVolumeClaim:
            claimName: ${MINIO_SERVICE_NAME}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - minio
        from:
          kind: ImageStreamTag
          name: ${MINIO_IMAGE}:${MINIO_VERSION}
          namespace: ${NAMESPACE}
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}
parameters:
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  value: openshift
- description: The name of the OpenShift Service exposed for the object storage server
  displayName: Database Service Name
  name: MINIO_SERVICE_NAME
  required: true
  value: minio
- description: Minio access key - minimum five characters in length
  displayName: Minio Access Key
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: MINIO_ACCESS_KEY
  required: true
- description: Minio secret key - minimum eight characters in length
  displayName: Minio Secret Key
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: MINIO_SECRET_KEY
  required: true
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Data Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: The name of the Minio imagestream to be used
  displayName: Name of Minio Image
  name: MINIO_IMAGE
  value: ocp-minio
- description: Version of Minio image to be used (RELEASE.2017-10-27T18-59-02Z, latest, or edge).
  displayName: Version of Minio Image
  name: MINIO_VERSION
  required: true
  value: "RELEASE.2017-10-27T18-59-02Z"

